name: Flake Checks

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            extra-experimental-features = nix-command flakes pipe-operators

      - name: Run Checks
        run: nix flake check --no-pure-eval --allow-import-from-derivation
