name: Formatting

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            extra-experimental-features = nix-command flakes pipe-operators

      - name: Format Code
        run: nix fmt -L -- --ci
