name: Automated Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            extra-experimental-features = nix-command flakes pipe-operators

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          commit-msg: "chore(deps): update flake.lock"
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            merge-queue
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}

  update-hudu-image:
    runs-on: ubuntu-latest
    needs: update-flake-lock
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            extra-experimental-features = nix-command flakes pipe-operators

      - name: Update Hudu image
        run: nix run nixpkgs#nix-prefetch-docker -- --image-name "hududocker/hudu" > hosts/hudu/application/docker-image.nix

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "hosts/hudu/application/docker-image.nix"
